# Generated by Django 6.1 on 2026-08-23 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_full_name_order_address_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('return', 'İade'), ('cancel', 'İptal')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'İnceleniyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('completed', 'Tamamlandı')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Internal note, visible to the customer once set')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
