# Generated by Django 6.1 on 2026-08-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_returnrequest'),
        ('products', '0008_colorswatch_product_color_swatches'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_note',
            field=models.CharField(blank=True, help_text="e.g. selected color code, 'B-130'", max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_note',
            field=models.CharField(blank=True, help_text="e.g. selected color code, 'B-130'", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant_note')},
        ),
    ]
