# Generated by Django 6.1 on 2026-08-25 15:09

import orders.models
import orders.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_cartitem_unique_together_cartitem_variant_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_email_uid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, storage=orders.storage.PrivateInvoiceStorage(), upload_to=orders.models.invoice_upload_to),
        ),
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, help_text='Luca açıklamasına yazılacak kod, örn. AK-1042', max_length=20, null=True, unique=True),
        ),
    ]
