# Generated by Django 6.1 on 2026-08-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_backfill_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cargo_company',
            field=models.CharField(blank=True, choices=[('', 'Belirtilmedi'), ('yurtici', 'Yurtiçi Kargo'), ('aras', 'Aras Kargo'), ('mng', 'MNG Kargo'), ('ptt', 'PTT Kargo'), ('surat', 'Sürat Kargo'), ('ups', 'UPS'), ('other', 'Diğer')], max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
