# Generated by Django 6.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_turmob_invoice_labels"),
        ("products", "0014_productvariant"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="products.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="variant_note",
            field=models.CharField(
                blank=True,
                help_text="Seçilen kalınlık / ebat / renk",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant_note",
            field=models.CharField(
                blank=True,
                help_text="Seçilen kalınlık / ebat / renk",
                max_length=200,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product", "variant", "variant_note")},
        ),
    ]
