# Generated by Django 6.1 on 2026-08-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='e.g. Antrasit Gri', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='e.g. 60 x 30 x 4 cm', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='e.g. Kumaş kaplı sünger', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text="Featured in 'ÜRÜNLERİMİZ' section"),
        ),
    ]
