# Generated by Django 6.1 on 2026-08-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_color_product_dimensions_product_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text="Featured in 'Cok Satanlar'"),
        ),
    ]
