# Generated by Django 6.1 on 2026-08-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. Yeni Koleksiyon', max_length=50)),
                ('title', models.CharField(blank=True, help_text='e.g. Akustik Panel Sistemleri', max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. Şıklık ve Sessizlik Bir Arada', max_length=200)),
                ('cta_text', models.CharField(blank=True, help_text='e.g. Ürünleri Gör (leave blank to hide button)', max_length=50)),
                ('cta_link', models.CharField(blank=True, help_text='e.g. /urunler', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
