# Generated by Django 6.1 on 2026-08-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSwatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. B-130', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional friendly name, e.g. Lacivert', max_length=100)),
                ('image', models.ImageField(upload_to='swatches/')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color_swatches',
            field=models.ManyToManyField(blank=True, help_text='Kumaş/renk seçenekleri -- seçiliyse ürün sayfasında müşteri renk seçmek zorunda kalır.', related_name='products', to='products.colorswatch'),
        ),
    ]
