# Generated by Django 6.1

from django.db import migrations, models
import django.db.models.deletion


def copy_specs_to_variants(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    ProductVariant = apps.get_model("products", "ProductVariant")
    for product in Product.objects.all():
        if ProductVariant.objects.filter(product=product).exists():
            continue
        ProductVariant.objects.create(
            product=product,
            thickness=product.thickness,
            dimensions=product.dimensions,
            density=product.density,
            color=product.color,
            price=product.price,
            discount_percent=product.discount_percent,
            stock=product.stock,
            order=0,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_review_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("thickness", models.CharField(blank=True, max_length=80, verbose_name="Kalınlık")),
                ("dimensions", models.CharField(blank=True, max_length=100, verbose_name="Ebat")),
                ("density", models.CharField(blank=True, max_length=80, verbose_name="Yoğunluk")),
                ("color", models.CharField(blank=True, max_length=100, verbose_name="Renk")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Fiyat (TL)")),
                ("discount_percent", models.PositiveIntegerField(default=0, verbose_name="İndirim %")),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stok")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Varyant",
                "verbose_name_plural": "Varyantlar (kalınlık, ebat, renk)",
            },
        ),
        migrations.RunPython(copy_specs_to_variants, migrations.RunPython.noop),
    ]
