# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_productvariant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Hikâye",
                "verbose_name_plural": "Hikâyeler (Instagram)",
            },
        ),
        migrations.AlterField(
            model_name="story",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Halkada görünür. Sadece video yüklersen boş bırakılabilir.",
                null=True,
                upload_to="stories/",
                verbose_name="Kapak / fotoğraf",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="MP4 / WebM / MOV. Hikâye açılınca oynar. Mümkünse 40 MB altı.",
                null=True,
                upload_to="stories/videos/",
                verbose_name="Video",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="link_url",
            field=models.CharField(
                blank=True,
                help_text="İsteğe bağlı, örn. /kategori/sungerler",
                max_length=200,
                verbose_name="Bağlantı",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Başlık"),
        ),
        migrations.AlterField(
            model_name="story",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Sıra"),
        ),
    ]
