# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_story_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="instagram_id",
            field=models.CharField(
                blank=True,
                help_text="Instagram’dan otomatik gelen gönderiler. Elle boş bırakın.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Instagram medya no",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="source",
            field=models.CharField(
                choices=[("manual", "Elle yüklendi"), ("instagram", "Instagram")],
                default="manual",
                max_length=20,
                verbose_name="Kaynak",
            ),
        ),
    ]
